<?php



$control = $_GET['control'];
$editpage = $_GET['editpage'];
$delete = $_GET['delete'];
$item = $_GET['item'];
$add = $_GET['add'];
$breaker = $_GET['breaker'];
$editpage = $_GET['editpage'];
$position = $_POST['position'];
$boldto = $_POST['position'];
$newpageto = $_POST['newpageto'];
$linkto = $_POST['linkto'];
$titleto = $_POST['titleto'];
$idt = $_POST['idt'];
$menu = $_GET['menu'];


if($menu=="change"){

for($t=0;$t<count($idt);$t++){

if(!$boldto[$t]){
$bold = 0;
}
else {
$bold = 1;
}

$sql = $stream->do_query("update anto_menu set link='$linkto[$t]', title='$titleto[$t]', bold='$bold', place='$position[$t]' where id='$idt[$t]'","one");
}

print "<h5>Menu Updated</h5><hr><br>";

}




if($add){

if($breaker){
$position = count($stream->do_query("select * from anto_menu","array"))+1;
$sql = $stream->do_query("insert into anto_menu values('','0','0','0','$position')","one");
print "<h5>Menu Item Added (Line Break)</h5><br><hr>";
}
else {

if($boldto){
	$bold = "1";
}
else {
	$bold = "0";
}

$position = count($stream->do_query("select * from anto_menu","array"))+1;
 
  $sql = $stream->do_query("insert into anto_menu values('','$linkto','$titleto','$bold','$position')","one");
  
  if($newpageto){
  	$stream->do_query("insert into anto_pages values('','$titleto','')","one");
  }
 print "<h5>Menu Item Added</h5><br><hr>";
}
}

if($delete){
$sql = $stream->do_query("delete from anto_menu where id=$item","one");
  
 print "<h5>Menu Item Deleted</h5><br><hr>";
}
  
  $sql = $stream->do_query("select * from anto_menu order by place asc","array");

  
  print "<br><br><h5>Menu Editor</h5><hr><br><form action=admin.php?control=editmenu&menu=change method=post><table cellpadding=2 width=600>";

for($t=0;$t<count($sql);$t++){
	$tmp = $sql[$t];
	$id = $tmp[0];
	$link = $tmp[1];
	$title = $tmp[2];
	$bold = $tmp[3];
	$place = $tmp[4];
	$tr = $t;
	
	
	
	$select = "";
	$select = "<select name=position[]>";
	
	for($y=0;$y<30;$y++){
	if("$place"==$y){
		$check = "selected";
	}
	else {
		$check = "";
	}
	$select = $select ."<option value='$y' $check>$y</option>";
	
	}
	$select = $select ."</select>";
	
	if($bold==1){
		$checked = "<input type=text  value='1' size=4 name=boldto[]>";	
	}
	else {
		$checked = "<input type=text value='0' size=4 name=boldto[]>";	
	}
	
	if($t%2==0){
		$bg = "#cccccc";
	}
	else {
		$bg = "#ffffff";
	}
	if($link=="0"){
		$bg="#ff6600";
	}
	
	
	if($link=="0"){
		print "<tr bgcolor='$bg'>
		<td><input type=hidden value='$id' name=idt[]>Line Break</td><td><input type=hidden name=linkto[] value='0'></td>
		<td>Line Break</td><td><input type=hidden name=titleto[] value='0'></td>
		<td><input type=hidden name=boldto[] value='0'>Line Break</td><td></td>
		<td>Position</td><td>$select</td>";
		print "</tr>";
	}
	else{
		print "<tr bgcolor='$bg'>
		<td><input type=hidden value='$id' name=idt[]>Link</td><td><input type=text name=linkto[] size=35 value='$link'></td>
		<td>Title</td><td><input type=text name=titleto[] size=20 value='$title'></td>
		<td>Bold</td><td>$checked</td>
		<td>Position</td><td>$select</td>";
		print "</tr>";
	}
}

print "<tr><td colspan=4><input type=submit value='update menu'> <input type=reset value='Reset'></form></td></tr></table>";


?>
<br><h5>Add New Menu Item</h5><hr><br>

<form action='admin.php?control=editmenu&add=true' method='post' name='fed'>
<table cellpadding=2 width=600>

<?php


$select = "";
	$select = "<select name=position>";
	for($y=0;$y<30;$y++){
	$select = $select ."<option value='$y'>$y</option>";
	}
	$select = $select ."</select>";

print "<tr bgcolor='$bg'>
		<td width=250>Link</td><td><input type='text' name='linkto' size='35' readonly='yes'> <br>Readonly:link generated by title</td></tr><tr>
		<td>Title</td><td><input type='text' name='titleto' size='20' 
		onKeyUp=\"document.fed.linkto.value='index.php?pagename=' + this.value\"></td></tr><tr>
		<td>Bold</td><td><input type=checkbox name='boldto'></td></tr><tr>
		<td>Make New Page For This Link</td><td><input type=checkbox name='newpageto'></td></tr><tr>
		<td>Position</td><td>$select</td>";
		print "</tr>";

?>
<tr><td colspan=4><input type=submit value='Add New Menu Item'><br /><br /><a href='admin.php?control=editmenu&add=true&breaker=true'>Forget all that just insert a line break</a></form></td></tr></table>



<br><h5>Delete Menu Item</h5><hr><br>
<script language='javascript'>
function makelink(title){
document.fed.link.value= "pages.php?pagename=" + title;
}

</script>
<table cellpadding=2 width=600>

<?php

for($t=0;$t<count($sql);$t++){
	$tmp = $sql[$t];
	$id = $tmp[0];
	$link = $tmp[1];
	$title = $tmp[2];
	$bold = $tmp[3];
	$place = $tmp[4];
	$tr = $t;
	
	if($link=="0"){
		print "<tr>
		<td>Line Break</td><td><input type=hidden name=link value='0'></td>
		<td>Line Break</td><td><input type=hidden name=title value='0'></td>
		<td>Delete</td><td><a href='admin.php?control=editmenu&delete=true&item=$id'>Delete Item</a></td>";
		print "</tr>";
	}
	else{
		print "<tr>
		<td>Link</td><td><input type=text name=link size=25 value='$link'></td>
		<td>Title</td><td><input type=text name=title size=20 value='$title'></td>
			<td>Delete</td><td><a href='admin.php?control=editmenu&delete=true&item=$id'>Delete Item</a></td>";
		print "</tr>";
	}
}

?></table>
